### ISSUE TITLE
okta CA scep

### ISSUE THREAD

**Issue by eckermike** [Sleepw4lker/PSCertificateEnrollment#4]
Is it possible to use the use this module with the Okta CA for device context?  We have a SCEP URL and a Challenge key.  I tried to use the get-ndescertificate cmdlet but I dont see where I can put in the scep url.

**Comment by Sleepw4lker** [comment]
Hello, the Cmdlet has a "Suffix" Parameter which should enable you to change the url to your needs. Do you maybe have an example for a SCEP URL for the Okta CA?
