### ISSUE TITLE
Specify Template for Certificate Request

### ISSUE THREAD

**Issue by ckrueger1979** [Sleepw4lker/PSCertificateEnrollment#6]
Hi,

would you please implement an option to specify the CA template in the request?

greetings
Carsten

**Comment by EUCTechTopics** [comment]
I would like this too !

**Comment by Sleepw4lker** [comment]
Hello @ckrueger1979 and @EUCTechTopics could you maybe provide more details about this? You can specify the certificate template name during submission via Get-IssuedCertificate. That was sufficient for my use cases so far. What exactly do you imagine and in which cmdlet? Cheers

**Comment by ckrueger1979** [comment]
Hi Sleepw4lker,

yes that's one option. If different persons create the csr and request the certificate it would be nice to had it specified in the request.

greetings
Carsten

**Comment by Sleepw4lker** [comment]
I'd argue that you rob yourself of a lot of flexibility when you embed the template information directly in the certificate request as the CA won't accept anything else then. If you specified the wrong one, you'd have to create a new CSR. When you specify it via submission you are free to choose which template you want to use.

**Comment by ckrueger1979** [comment]
Fine for me. Lowers my risk (csr creator) that some else (csr submitter) makes a mistake.

**Comment by Sleepw4lker** [comment]
Splendid. Then I'd close this as won't fix/implement for now ;).
